#!/bin/bash

API_TOKEN="uTd9TIKdFQ5H0-Wx_M8MBp-PnjXnQz64WXDbJsaG"
ZONE_ID="dbdf7fd9bf0b8a5d3241e652f3dd10d4"    
DOMAIN="bb7.tech"
RECORD_NAME="@"

NEW_IP=$(curl -s http://ipecho.net/plain || curl -s http://ifconfig.me)

DNS_RECORD=(curl−s−XGET"https://api.cloudflare.com/client/v4/zones/(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/ZONE_ID/dns_records?type=A&name=RECORDNAME.RECORD_NAME.DOMAIN" \
  -H "Authorization: Bearer $API_TOKEN" \
  -H "Content-Type: application/json")

RECORD_ID=(echo(echo DNS_RECORD | jq -r '.result[0].id')
OLD_IP=(echo(echo DNS_RECORD | jq -r '.result[0].content')

if [ "NEWIP"!="NEW_IP" != "OLD_IP" ]; then
  curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/ZONEID/dnsrecords/ZONE_ID/dns_records/RECORD_ID" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json" \
    --data "{\"type\":\"A\",\"name\":\"RECORDNAME.RECORD_NAME.DOMAIN\",\"content\":\"$NEW_IP\",\"ttl\":120}"
  echo "(date):IPupdated→(date): IP updated → NEW_IP" >> /var/log/ddns.log
else
  echo "$(date): IP unchanged" >> /var/log/ddns.log
fi
